import URLComponent from '../components/url-component';
import { useTheme } from '@mui/material/styles';
import { useContext } from 'react';
import { IconButton, Box } from '@mui/material';
import Head from 'next/head';
import { ColorModeContext } from '../pages/_app';
import Brightness4Icon from '@mui/icons-material/Brightness4';
import Brightness7Icon from '@mui/icons-material/Brightness7';

// TODO: Call GitHub Api to get the branches.

export default function Index() {
	const theme = useTheme();
	const colorMode = useContext(ColorModeContext);
	return (
		<>
			<Head>
				<title>Kanban Branches POC</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* TODO: Components should live here. */}
			<Box sx={{ margin: '4%' }}>
				<IconButton sx={{ ml: 1 }} onClick={colorMode.toggleColorMode} color="inherit">
					{theme.palette.mode === 'dark' ? <Brightness7Icon /> : <Brightness4Icon />}
				</IconButton>
				<URLComponent />
			</Box>
		</>
	)
}
