import URLComponent from '../components/url-component';
import { Inter } from '@next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

// TODO: Call GitHub Api to get the branches.

export default function Index() {
	return (
		<>
			<Head>
				<title>Kanban Branches POC</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* TODO: Components should live here. */}
			<URLComponent />
		</>
	)
}
